local utils = require "st.utils"

describe("test clamp value", function()
  it("should return the value if it is between bounds", function()
    assert.are.equal(utils.clamp_value(5, 0, 100), 5)
  end)
  it("should return the min if it is below min", function()
    assert.are.equal(utils.clamp_value(-10, 0, 100), 0)
  end)
  it("should return the max if it is above max", function()
    assert.are.equal(utils.clamp_value(150, 0, 100), 100)
  end)
end)

describe("test round", function()
  it("should round down below .5", function()
    assert.are.equal(utils.round(1.1), 1)
  end)
  it("should round up above .5", function()
    assert.are.equal(utils.round(1.7), 2)
  end)
  it("should round up at .5", function()
    assert.are.equal(utils.round(1.5), 2)
  end)
end)

describe("test get_print_safe_string", function()
  it("should leave a printable string alone", function()
    assert.are.equal(utils.get_print_safe_string("a test string"), "a test string")
  end)
  it("should convert raw bytes to hex ascii with escape", function()
    assert.are.equal(utils.get_print_safe_string("\01\02\03"), "\\x01\\x02\\x03")
  end)
end)
